[2024-09-26T14:00:29.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T14:00:29.267+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.hello_task manual__2024-09-26T14:00:28.234701+00:00 [queued]>
[2024-09-26T14:00:29.274+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.hello_task manual__2024-09-26T14:00:28.234701+00:00 [queued]>
[2024-09-26T14:00:29.275+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T14:00:29.287+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): hello_task> on 2024-09-26 14:00:28.234701+00:00
[2024-09-26T14:00:29.292+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'hello_task', 'manual__2024-09-26T14:00:28.234701+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpeyd7icj0']
[2024-09-26T14:00:29.294+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask hello_task
[2024-09-26T14:00:29.295+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-26T14:00:29.296+0000] {standard_task_runner.py:72} INFO - Started process 485 to run task
[2024-09-26T14:00:29.329+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.hello_task manual__2024-09-26T14:00:28.234701+00:00 [running]> on host 57a3226b2e41
[2024-09-26T14:00:29.399+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T14:00:28.234701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-26T14:00:28.234701+00:00'
[2024-09-26T14:00:29.400+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T14:00:29.480+0000] {logging_mixin.py:190} INFO - weather: {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-09-26T14:00:29.481+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-26T14:00:29.489+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T14:00:29.490+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=hello_world_dag, task_id=hello_task, run_id=manual__2024-09-26T14:00:28.234701+00:00, execution_date=20240926T140028, start_date=20240926T140029, end_date=20240926T140029
[2024-09-26T14:00:29.511+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-26T14:00:29.523+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T14:00:29.525+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
