[2024-09-26T13:59:45.375+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T13:59:45.388+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.hello_task manual__2024-09-26T13:59:44.833108+00:00 [queued]>
[2024-09-26T13:59:45.395+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.hello_task manual__2024-09-26T13:59:44.833108+00:00 [queued]>
[2024-09-26T13:59:45.396+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T13:59:45.409+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): hello_task> on 2024-09-26 13:59:44.833108+00:00
[2024-09-26T13:59:45.414+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'hello_task', 'manual__2024-09-26T13:59:44.833108+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmp0kxru6xz']
[2024-09-26T13:59:45.417+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask hello_task
[2024-09-26T13:59:45.418+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=464) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-26T13:59:45.418+0000] {standard_task_runner.py:72} INFO - Started process 465 to run task
[2024-09-26T13:59:45.456+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.hello_task manual__2024-09-26T13:59:44.833108+00:00 [running]> on host 57a3226b2e41
[2024-09-26T13:59:45.530+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T13:59:44.833108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-26T13:59:44.833108+00:00'
[2024-09-26T13:59:45.530+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T13:59:45.619+0000] {logging_mixin.py:190} INFO - weather: {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-09-26T13:59:45.620+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-26T13:59:45.627+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T13:59:45.628+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=hello_world_dag, task_id=hello_task, run_id=manual__2024-09-26T13:59:44.833108+00:00, execution_date=20240926T135944, start_date=20240926T135945, end_date=20240926T135945
[2024-09-26T13:59:45.672+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-26T13:59:45.685+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T13:59:45.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
